name: Test

on:
  push:
    branches-ignore: [ "main" ]

env:
  NODE_VERSION: ">=18.12.1"

permissions:
  id-token: write
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.25.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: pnpm
      - name: Pnpm install
        run: |
          pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test --runInBand --detectOpenHandles --forceExit
